version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: npm-analysis
      MYSQL_DATABASE: npm
    volumes:
      - ./npmMysql:/var/lib/mysql
    ports:
      - 3306:3306

  graph:
    image: neo4j:3.3
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_dbms_memory_heap_initialSize=2G
      - NEO4J_dbms_memory_heap_maxSize=2G
      - NEO4J_dbms_security_procedures_unrestricted=algo.*,apoc.\\\*

  mongodb:
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: npm
      MONGO_INITDB_ROOT_PASSWORD: npm123
    volumes:
      - ./mongod/data:/data/db