# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: npm-analysis
      MYSQL_DATABASE: npm
    volumes:
      - ./npmMysql:/var/lib/mysql
    ports:
      - 3306:3306

  graph:
    image: neo4j:3.3
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
    environment:
      - NEO4J_dbms_memory_pagecache_size=4G
      - NEO4J_dbms.memory.heap.max_size=12G