# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: npm-analysis
      MYSQL_DATABASE: npm
    volumes:
      - ./npmMysql:/var/lib/mysql
    ports:
      - 3306:3306