version: '3.1'

services:
  callgraph:
    image: neo4j:3.4.5
    restart: always
    ports:
      - 7475:7474
      - 7688:7687
    volumes:
      - ./db-data/neo4j-callgraph/data:/data
      - ./db-data/neo4j-callgraph/plugins:/plugins
    environment:
      - NEO4J_dbms_memory_heap_maxSize=2G
      - NEO4J_dbms_security_procedures_unrestricted=algo.*,apoc.\\\*
      - NEO4J_dbms_connector_bolt_advertised__address=:7688
